### ISSUE TITLE
"Bad CPU type in executable" and other issues

### ISSUE THREAD

**Issue by pr-crypto** [adiyoss/DeepVOT#1]
Hi, 

I am kinda rookie. 

I am running Mac OS10.15: Catalina.

I tried running the test example using 

`python predict.py test_data/orig/bun.wav test_data/prediction/bun.TextGrid 0.0 0.2`

I get the following errors:

`1) Extracting features and classifying ...
/bin/sh: sbin/sox: Bad CPU type in executable
00:24:20.532 [VotFrontEnd2] INFO: Processing 1 instances.
Errror: Could not open file tmp/tmp.wav for reading.

==> processing options	
==> load test file	

==> ERROR: cannot read file.	
/Users/XXXX/torch/install/bin/lua: utils.lua:47: attempt to index global 'dims' (a nil value)
stack traceback:
	utils.lua:47: in function 'load_data'
	classify_multi_class.lua:53: in main chunk
	[C]: in function 'dofile'
	...rs02/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

3) Extract Durations ...
Traceback (most recent call last):
  File "predict.py", line 57, in <module>
    predict(args.input_path, args.output_path, args.start_extract, args.end_extract)
  File "predict.py", line 38, in predict
    post_process(prob_file, predict_file)
  File "/Users/XXXX/DeepVOT/run_all/post_process.py", line 12, in post_process
    with open(prob_file) as f:
IOError: [Errno 2] No such file or directory: '/Users/XXXX/DeepVOT/run_all/tmp_files/tmp.prob'`

Any pointer will be highly appreciated!

**Comment by jkeshet** [comment]
The problem is that the script is based on a software called "sox" to convert the sound to 16kHz/16bits. You need to replace the file `DeepVOT/front_end/sbin/sox` with a binary that you can be taken from either here:
http://sox.sourceforge.net
or by the Mac utility called "brew" and then "brew install sox" and then copy 
from `/usr/local/bin/sox` to `DeepVOT/front_end/sbin/sox`.

**Comment by jkeshet** [comment]
You need to replace the file `DeepVOT/front_end/sbin/sox` with a binary that you can be taken from either here:
http://sox.sourceforge.net
or by the Mac utility called "brew" and then "brew install sox" and then copy 
from /usr/local/bin/sox to DeepVOT/front_end/sbin/sox

**Comment by adiyoss** [comment]
Thanks @jkeshet! 
I agree, I think the easiest would be to install sox using 'brew' and copy it to DeepVOT/front_end/sbin/sox

**Comment by FredrikKarlssonSpeech** [comment]
You also need to move the brew sox to run_all/sbin/ to make it work. 
Maybe a good idea to move the binary out of the subfolder?
