### ISSUE TITLE
Too many paths to consider

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [adiyoss/DeepVOT#3]
Hi,

While I love the effort, there are many dependencies and library paths that need to be set up to get this to work. 

On OSX Catallina (and after having installed according to the instructions) i get this:

```
$ python predict.py test_data/orig/bun.wav test_data/prediction/bun.TextGrid 0.0 0.2

1) Extracting features and classifying ...
12:17:37.946 [VotFrontEnd2] INFO: Processing 1 instances.
12:17:37.964 [VotFrontEnd2] INFO: Features extraction completed.

==> processing options	
==> load test file	

==> loading model	
/Users/frkkan96/torch/install/bin/luajit: /Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.LinearNoBias>
stack traceback:
	[C]: in function 'error'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	...
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/nn/Module.lua:192: in function 'read'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/Users/frkkan96/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	classify_multi_class.lua:64: in main chunk
	[C]: in function 'dofile'
	...an96/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010c4e9b00

3) Extract Durations ...
Traceback (most recent call last):
  File "predict.py", line 57, in <module>
    predict(args.input_path, args.output_path, args.start_extract, args.end_extract)
  File "predict.py", line 38, in predict
    post_process(prob_file, predict_file)
  File "/Users/frkkan96/Documents/src/DeepVOT/run_all/post_process.py", line 12, in post_process
    with open(prob_file) as f:
IOError: [Errno 2] No such file or directory: '/Users/frkkan96/Documents/src/DeepVOT/run_all/tmp_files/tmp.prob'
```

It seems that torch cannot find the rnn library I installed. So, how do I make it find the library?

**Comment by jkeshet** [comment]
Please consider our more recent and better effort for estimation of positive negative VOT here: 
https://github.com/MLSpeech/Dr.VOT
You can send me an email <jkeshet@cs.biu.ac.il>  if you need help in installation or execution of the code
